# Generated by Django 5.0.2 on 2024-03-31 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TrouserSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='footwear_sizes',
            field=models.ManyToManyField(blank=True, to='store.footwearsize'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('cvv_code', models.CharField(blank=True, max_length=3, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('VISA', 'VISA'), ('MasterCard', 'MasterCard'), ('Rupay', 'Rupay')], max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('debit_credit_card', 'Debit/Credit Card'), ('upi', 'UPI')], max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(choices=[('BLUEDART', 'bluedart'), ('Delhivery', 'delhivery'), ('INDIA POST', 'india_post'), ('Other', 'Other')], default='Other', max_length=100)),
                ('tracking_id', models.CharField(blank=True, max_length=100)),
                ('shipping_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField()),
                ('delivery_status', models.CharField(choices=[('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='in_transit', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shirt_sizes',
            field=models.ManyToManyField(blank=True, to='store.shirtsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='trouser_sizes',
            field=models.ManyToManyField(blank=True, to='store.trousersize'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
