# Generated by Django 5.0.2 on 2024-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_footwearsize_shirtsize_trousersize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
